# -*- coding: utf-8 -*-
"""VAD-Audio-Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yES2Szu92xFmolWTLP3VUewrRIQW8p6
"""

pip install torch torchaudio

!pip install silero-vad

from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

from silero_vad import load_silero_vad, read_audio, get_speech_timestamps
model = load_silero_vad()
wav = read_audio('Recording.m4a')
speech_timestamps = get_speech_timestamps(
  wav,
  model,
  return_seconds=True,  # Return speech timestamps in seconds (default is samples)
)

print(speech_timestamps)

import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(15, 3))

for i, ts in enumerate(speech_timestamps):
    ax.hlines(y=0.5, xmin=ts['start'], xmax=ts['end'], linewidth=5, color='blue', label='Speech' if i == 0 else "")

ax.set_yticks([]) # Remove y-axis ticks as it's a single timeline
ax.set_xlabel('Time (seconds)')
ax.set_title('Speech Activity Timeline')
ax.set_xlim(0, max(ts['end'] for ts in speech_timestamps) + 2) # Adjust x-axis limit for better visualization
ax.legend(['Speech Segments'], loc='upper right')
plt.grid(True, axis='x', linestyle='--', alpha=0.7)
plt.show()

import torch
torch.set_num_threads(1)

model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad', model='silero_vad')
(get_speech_timestamps, _, read_audio, _, _) = utils

wav = read_audio('Recording.m4a')
speech_timestamps = get_speech_timestamps(
  wav,
  model,
  return_seconds=True,  # Return speech timestamps in seconds (default is samples)
)

print(speech_timestamps)